require 'test_helper'

class ApplicantTest < ActiveSupport::TestCase

  def setup
    @one = applicants(:one)
    valid = @one.valid?
    assert valid, @one.errors.messages
  end

  test "fills basic personal information" do
    assert_equal "One John McOne", @one.field("Name")
    assert_equal "One John McOne", @one.field("FullName")
    assert_equal "One John McOne", @one.field("FullName1")
    assert_equal "O", @one.field("FirstInitial")
    assert_equal "J", @one.field("MiddleInitial")
    assert_equal "M", @one.field("LastInitial")
    assert_equal "(202) 586-5000", @one.field("WorkPhone")
    assert_equal "02/03/1981", @one.field("DOB")
    assert_equal "02", @one.field("DOBMM")
    assert_equal "03", @one.field("DOBDD")
    assert_equal "1981", @one.field("DOBYYYY")
    assert_equal "one@districthousing.org", @one.field("Email")
    assert_equal "One", @one.field("FirstName")
    assert_equal "McOne", @one.field("LastName")
    assert_equal "(202) 208-4743", @one.field("CellPhone")
    assert_equal "(202) 272-0167", @one.field("HomePhone")
    assert_equal "(202) 456-1111", @one.field("Phone")
    assert_equal "111-11-1111", @one.field("SSN")
    assert_equal "Male", @one.field("Gender")
    assert_equal "M", @one.field("GenderInitial")
    assert_equal "USA", @one.field("Nationality")
    assert_equal "Virginia", @one.field("BirthState")
    assert_equal "Springfield", @one.field("BirthCity")
  end

  test "fills addresses" do
    assert_equal "111 Fake Street, Oneville, DC, 11111", @one.field("Address")
    assert_equal "Oneville", @one.field("AddressCity")
    assert_equal "DC", @one.field("AddressState")
    assert_equal "111 Fake Street", @one.field("AddressStreet")
    assert_equal "11111", @one.field("AddressZip")
  end

  test "fills contact information" do
    assert_equal "", @one.field("Contact1Add")
    assert_equal "", @one.field("Contact1Address")
    assert_equal "", @one.field("Contact1CellPhone")
    assert_equal "", @one.field("Contact1Name")
    assert_equal "", @one.field("Contact1Phone")
    assert_equal "", @one.field("Contact1Relationship")
    assert_equal "", @one.field("Contact2Add")
    assert_equal "", @one.field("Contact2Name")
    assert_equal "", @one.field("Contact2Phone")
  end

  test "fills household member information" do
    assert_equal "", @one.field("HH1Age")
    assert_equal "", @one.field("HH1CitizenYN")
    assert_equal "", @one.field("HH1DOB")
    assert_equal "HH1", @one.field("HH1FirstName")
    assert_equal "", @one.field("HH1Gender")
    assert_equal "", @one.field("HH1LastName")
    assert_equal "HH1", @one.field("HH1Name")
    assert_equal "", @one.field("HH1Relationship")
    assert_equal "", @one.field("HH1SSN")
    assert_equal "", @one.field("HH2Age")
    assert_equal "", @one.field("HH2CitizenYN")
    assert_equal "", @one.field("HH2DOB")
    assert_equal "HH2", @one.field("HH2FirstName")
    assert_equal "", @one.field("HH2Gender")
    assert_equal "", @one.field("HH2LastName")
    assert_equal "HH2", @one.field("HH2Name")
    assert_equal "", @one.field("HH2Relationship")
    assert_equal "", @one.field("HH2SSN")
    assert_equal "", @one.field("HH3Age")
    assert_equal "", @one.field("HH3CitizenYN")
    assert_equal "", @one.field("HH3DOB")
    assert_equal "", @one.field("HH3FirstName")
    assert_equal "", @one.field("HH3Gender")
    assert_equal "", @one.field("HH3LastName")
    assert_equal "", @one.field("HH3Name")
    assert_equal "", @one.field("HH3Relationship")
    assert_equal "", @one.field("HH3SSN")
    assert_equal "", @one.field("HH4Age")
    assert_equal "", @one.field("HH4CitizenYN")
    assert_equal "", @one.field("HH4DOB")
    assert_equal "", @one.field("HH4FirstName")
    assert_equal "", @one.field("HH4Gender")
    assert_equal "", @one.field("HH4LastName")
    assert_equal "", @one.field("HH4Name")
    assert_equal "", @one.field("HH4Relationship")
    assert_equal "", @one.field("HH4SSN")
    assert_equal "", @one.field("HH5Age")
    assert_equal "", @one.field("HH5CitizenYN")
    assert_equal "", @one.field("HH5DOB")
    assert_equal "", @one.field("HH5FirstName")
    assert_equal "", @one.field("HH5Gender")
    assert_equal "", @one.field("HH5LastName")
    assert_equal "", @one.field("HH5Name")
    assert_equal "", @one.field("HH5Relationship")
    assert_equal "", @one.field("HH5SSN")
  end

  test "fills landlord information" do
    assert_equal "111 Fake Street, Oneville, DC, 11111", @one.field("LL1Address")
    assert_equal "LL1", @one.field("LL1Name")
    assert_equal "(555) 555-5555", @one.field("LL1Phone")
    assert_equal "222 Fake Street, Two Town, AK, 22222", @one.field("LL2Address")
    assert_equal "LL2", @one.field("LL2Name")
    assert_equal "(666) 666-6666", @one.field("LL2Phone")
  end

  test "other fields" do
    assert_equal "", @one.field("Accommodations")
    assert_equal "", @one.field("Accommodations2")
    assert_equal "", @one.field("AlimonyN")
    assert_equal "", @one.field("AlimonyY")
    assert_equal "", @one.field("Arabic")
    assert_equal "", @one.field("Armenian")
    assert_equal "", @one.field("AssetsIncN")
    assert_equal "", @one.field("AssetsIncY")
    assert_equal "", @one.field("BankNameCheck")
    assert_equal "", @one.field("BankNameOth")
    assert_equal "", @one.field("BankNameSav")
    assert_equal "", @one.field("Cambodian")
    assert_equal "", @one.field("CashGiftsN")
    assert_equal "", @one.field("CashGiftsY")
    assert_equal "", @one.field("Chamorro")
    assert_equal "", @one.field("CheckingAcct")
    assert_equal "", @one.field("CheckingBalance")
    assert_equal "", @one.field("ChildSupIncN")
    assert_equal "", @one.field("ChildSupIncY")
    assert_equal "", @one.field("ChineseSimp")
    assert_equal "", @one.field("ChineseTrad")
    assert_equal "", @one.field("CitYN")
    assert_equal "", @one.field("ConvictionsN")
    assert_equal "", @one.field("Croatian")
    assert_equal "", @one.field("Czech")
    assert_equal "", @one.field("Disability")
    assert_equal "", @one.field("Dutch")
    assert_equal "", @one.field("EmpIncN")
    assert_equal "", @one.field("EmpIncY")
    assert_equal "", @one.field("English")
    assert_equal "", @one.field("EthnicityDeclineT")
    assert_equal "", @one.field("EthnicityHispanic")
    assert_equal "", @one.field("EthnicityHispanicT")
    assert_equal "", @one.field("EthnicityNonHispanic")
    assert_equal "", @one.field("EthnicityNonHispanicT")
    assert_equal "", @one.field("EvictDrugsN")
    assert_equal "", @one.field("EvictDrugsY")
    assert_equal "", @one.field("Farsi")
    assert_equal "", @one.field("French")
    assert_equal "", @one.field("German")
    assert_equal "", @one.field("Greek")
    assert_equal "", @one.field("Haitian")
    assert_equal "", @one.field("Hindi")
    assert_equal "", @one.field("Hmong")
    assert_equal "", @one.field("Hungarian")
    assert_equal "", @one.field("Ilocano")
    assert_equal "", @one.field("Italian")
    assert_equal "", @one.field("Japanese")
    assert_equal "", @one.field("Korean")
    assert_equal "", @one.field("LPR")
    assert_equal "", @one.field("Laotian")
    assert_equal "", @one.field("LiveWithYou")
    assert_equal "", @one.field("LiveWithYouN")
    assert_equal "", @one.field("LiveWithYouY")
    assert_equal "", @one.field("MCareN")
    assert_equal "", @one.field("MCareY")
    assert_equal "", @one.field("OtherAcct")
    assert_equal "", @one.field("OtherBalance")
    assert_equal "", @one.field("OutstandingBillsN")
    assert_equal "", @one.field("OutstandingBillsY")
    assert_equal "", @one.field("OwnHomeN")
    assert_equal "", @one.field("OwnHomeY")
    assert_equal "", @one.field("PayChildcareN")
    assert_equal "", @one.field("PayChildcareY")
    assert_equal "", @one.field("PdInsN")
    assert_equal "", @one.field("PdInsY")
    assert_equal "", @one.field("PensionN")
    assert_equal "", @one.field("PensionY")
    assert_equal "", @one.field("Polish")
    assert_equal "", @one.field("Portuguese")
    assert_equal "", @one.field("RaceAsianT")
    assert_equal "", @one.field("RaceBlackT")
    assert_equal "", @one.field("RaceDeclineT")
    assert_equal "", @one.field("RaceNativeAmericanT")
    assert_equal "", @one.field("RaceOtherT")
    assert_equal "", @one.field("RacePacificIslanderT")
    assert_equal "", @one.field("RaceWhiteT")
    assert_equal "", @one.field("Russian")
    assert_equal "", @one.field("SSABensN")
    assert_equal "", @one.field("SSABensY")
    assert_equal "", @one.field("SavingsAcct")
    assert_equal "", @one.field("SavingsBalance")
    assert_equal "", @one.field("Serbian")
    assert_equal "", @one.field("SexOffenderN")
    assert_equal "", @one.field("SexOffenderY")
    assert_equal "", @one.field("Slovak")
    assert_equal "", @one.field("SoldPropertyN")
    assert_equal "", @one.field("SoldPropertyY")
    assert_equal "", @one.field("Spanish")
    assert_equal "", @one.field("SubAbuseN")
    assert_equal "", @one.field("SubAbuseY")
    assert_equal "", @one.field("TANFIncN")
    assert_equal "", @one.field("TANFIncY")
    assert_equal "", @one.field("Tagalog")
    assert_equal "", @one.field("Text1")
    assert_equal "", @one.field("Text247")
    assert_equal "", @one.field("Text248")
    assert_equal "", @one.field("Text249")
    assert_equal "", @one.field("Text250")
    assert_equal "", @one.field("Text251")
    assert_equal "", @one.field("Text252")
    assert_equal "", @one.field("Text253")
    assert_equal "", @one.field("Text254")
    assert_equal "", @one.field("Text255")
    assert_equal "", @one.field("Text256")
    assert_equal "", @one.field("Text257")
    assert_equal "", @one.field("Text258")
    assert_equal "", @one.field("Text259")
    assert_equal "", @one.field("Text260")
    assert_equal "", @one.field("Text261")
    assert_equal "", @one.field("Text262")
    assert_equal "", @one.field("Text266")
    assert_equal "", @one.field("Text270")
    assert_equal "", @one.field("Text274")
    assert_equal "", @one.field("Text281")
    assert_equal "", @one.field("Text282")
    assert_equal "", @one.field("Text3")
    assert_equal "", @one.field("Text4")
    assert_equal "", @one.field("Text7")
    assert_equal "", @one.field("Text8")
    assert_equal "", @one.field("Text9")
    assert_equal "", @one.field("Thai")
    assert_equal "", @one.field("Tongan")
    assert_equal "", @one.field("Ukranian")
    assert_equal "", @one.field("UnempIncN")
    assert_equal "", @one.field("UnempIncY")
    assert_equal "", @one.field("UpcomingBillsN")
    assert_equal "", @one.field("UpcomingBillsY")
    assert_equal "", @one.field("Urdu")
    assert_equal "", @one.field("Viet")
    assert_equal "", @one.field("Yiddish")
  end
end
